### PR TITLE
26576 corners

### PR DESCRIPTION
**Pull request by Sicorschi-Tudor**
https://github.com/bagrinsergiu/blox-editor/issues/26576

### CODE REVIEW

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. Missing `icon` property
image
---
2. image
---
3. image

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. image
---
2. image
---
3. image
--- 
4. image
---
5. image
---
6. image
---
7. image

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. image
---
2. image
---
3. image
---
4. image

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. image
---
2. image
---
3. image
---
4. image

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. Missing `states` parameter and `states` example
2. Missing `selector` parameter and `selector` example
3. Missing `icon` parameter. I'm not sure if your control can handle it, but if it can, then add
4. Missing `className` parameter. I'm not sure if your control can handle it, but if it can, then add

**Comment by Sicorschi-Tudor** [comment]
> 1. Missing `states` parameter and `states` example
> 2. Missing `selector` parameter and `selector` example
> 3. Missing `icon` parameter. I'm not sure if your control can handle it, but if it can, then add
> 4. Missing `className` parameter. I'm not sure if your control can handle it, but if it can, then add

This control cannot handle `className`.

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. Your control can't handle `display` property. Remove it.
2. Missing `selector` in parameters. Should be before of `style`
3. image
4. image
5. image

**Pull request merged**
