### PR TITLE
Docs Extend for RadioGroup

### PR DESCRIPTION
**Pull request by GunkaArtur**
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26608

### CODE REVIEW

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. image
---
2. image
---
3. image
---
4. image
---
5. image

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. image
---
2. image
---
3. image
---
4. image
---
5. image
---
6. image

**Comment by GunkaArtur** [comment]
@victor-pg 

1 - is the same as in `switch`

**Review by victor-pg — CHANGES_REQUESTED** [review]
1. Your control can't handle `className` param. Remote it
2. image
3. image

**Pull request merged**
